// Generated by scripts/tune-decks.ts. Run `pnpm tune` to rebuild.
// cards: starting deck, turns: mean total turns, deaths: mean deaths, noWinner: share of games nobody wins.

import type { Mode } from "./rules";

export type GameLength = "short" | "medium" | "long";

export interface DeckPreset {
  cards: number;
  turns: number;
  deaths: number;
  noWinner: number;
}

export const DECK_TABLE: Record<Mode, Record<number, Record<GameLength, DeckPreset>>> = {
  hasard: {
    "2": {
      short: {
        cards: 20,
        turns: 4.2,
        deaths: 0.39,
        noWinner: 0.066,
      },
      medium: {
        cards: 57,
        turns: 6.2,
        deaths: 0.85,
        noWinner: 0.105,
      },
      long: {
        cards: 120,
        turns: 7.1,
        deaths: 0.98,
        noWinner: 0.115,
      },
    },
    "3": {
      short: {
        cards: 39,
        turns: 8.3,
        deaths: 0.96,
        noWinner: 0.074,
      },
      medium: {
        cards: 72,
        turns: 12,
        deaths: 1.56,
        noWinner: 0.1,
      },
      long: {
        cards: 111,
        turns: 13.9,
        deaths: 1.84,
        noWinner: 0.112,
      },
    },
    "4": {
      short: {
        cards: 54,
        turns: 11.9,
        deaths: 1.47,
        noWinner: 0.065,
      },
      medium: {
        cards: 96,
        turns: 17.6,
        deaths: 2.32,
        noWinner: 0.092,
      },
      long: {
        cards: 149,
        turns: 20.5,
        deaths: 2.79,
        noWinner: 0.11,
      },
    },
    "5": {
      short: {
        cards: 67,
        turns: 15,
        deaths: 1.9,
        noWinner: 0.06,
      },
      medium: {
        cards: 121,
        turns: 23.1,
        deaths: 3.12,
        noWinner: 0.082,
      },
      long: {
        cards: 186,
        turns: 27.1,
        deaths: 3.79,
        noWinner: 0.101,
      },
    },
    "6": {
      short: {
        cards: 80,
        turns: 18.1,
        deaths: 2.34,
        noWinner: 0.062,
      },
      medium: {
        cards: 149,
        turns: 29,
        deaths: 3.99,
        noWinner: 0.082,
      },
      long: {
        cards: 213,
        turns: 33.7,
        deaths: 4.69,
        noWinner: 0.106,
      },
    },
    "7": {
      short: {
        cards: 93,
        turns: 21,
        deaths: 2.72,
        noWinner: 0.053,
      },
      medium: {
        cards: 167,
        turns: 34,
        deaths: 4.66,
        noWinner: 0.072,
      },
      long: {
        cards: 229,
        turns: 39.5,
        deaths: 5.5,
        noWinner: 0.099,
      },
    },
    "8": {
      short: {
        cards: 106,
        turns: 24,
        deaths: 3.29,
        noWinner: 0.053,
      },
      medium: {
        cards: 193,
        turns: 39.9,
        deaths: 5.48,
        noWinner: 0.077,
      },
      long: {
        cards: 263,
        turns: 46.5,
        deaths: 6.44,
        noWinner: 0.089,
      },
    },
    "9": {
      short: {
        cards: 120,
        turns: 27.2,
        deaths: 3.75,
        noWinner: 0.054,
      },
      medium: {
        cards: 220,
        turns: 45.6,
        deaths: 6.26,
        noWinner: 0.08,
      },
      long: {
        cards: 292,
        turns: 52.9,
        deaths: 7.38,
        noWinner: 0.1,
      },
    },
    "10": {
      short: {
        cards: 135,
        turns: 30.5,
        deaths: 4.08,
        noWinner: 0.048,
      },
      medium: {
        cards: 243,
        turns: 51,
        deaths: 7.08,
        noWinner: 0.077,
      },
      long: {
        cards: 318,
        turns: 59.3,
        deaths: 8.23,
        noWinner: 0.093,
      },
    },
    "11": {
      short: {
        cards: 146,
        turns: 32.9,
        deaths: 4.49,
        noWinner: 0.058,
      },
      medium: {
        cards: 269,
        turns: 56.9,
        deaths: 7.89,
        noWinner: 0.064,
      },
      long: {
        cards: 348,
        turns: 65.5,
        deaths: 9.19,
        noWinner: 0.094,
      },
    },
    "12": {
      short: {
        cards: 160,
        turns: 36.1,
        deaths: 4.89,
        noWinner: 0.051,
      },
      medium: {
        cards: 291,
        turns: 62.2,
        deaths: 8.69,
        noWinner: 0.067,
      },
      long: {
        cards: 383,
        turns: 72.2,
        deaths: 10.2,
        noWinner: 0.092,
      },
    },
  },
  tactique: {
    "2": {
      short: {
        cards: 11,
        turns: 2.3,
        deaths: 0.29,
        noWinner: 0.04,
      },
      medium: {
        cards: 57,
        turns: 3.5,
        deaths: 0.99,
        noWinner: 0.001,
      },
      long: {
        cards: 107,
        turns: 4,
        deaths: 1,
        noWinner: 0,
      },
    },
    "3": {
      short: {
        cards: 22,
        turns: 4.7,
        deaths: 1.04,
        noWinner: 0.049,
      },
      medium: {
        cards: 34,
        turns: 6.6,
        deaths: 1.39,
        noWinner: 0.04,
      },
      long: {
        cards: 99,
        turns: 7.6,
        deaths: 2,
        noWinner: 0,
      },
    },
    "4": {
      short: {
        cards: 30,
        turns: 6.8,
        deaths: 1.35,
        noWinner: 0.055,
      },
      medium: {
        cards: 50,
        turns: 9.8,
        deaths: 2.35,
        noWinner: 0.035,
      },
      long: {
        cards: 85,
        turns: 11.5,
        deaths: 2.93,
        noWinner: 0.006,
      },
    },
    "5": {
      short: {
        cards: 41,
        turns: 9.1,
        deaths: 1.88,
        noWinner: 0.055,
      },
      medium: {
        cards: 64,
        turns: 13,
        deaths: 3.14,
        noWinner: 0.038,
      },
      long: {
        cards: 99,
        turns: 15.3,
        deaths: 3.86,
        noWinner: 0.011,
      },
    },
    "6": {
      short: {
        cards: 51,
        turns: 11.4,
        deaths: 2.47,
        noWinner: 0.051,
      },
      medium: {
        cards: 79,
        turns: 16.6,
        deaths: 3.82,
        noWinner: 0.043,
      },
      long: {
        cards: 113,
        turns: 19.1,
        deaths: 4.78,
        noWinner: 0.015,
      },
    },
    "7": {
      short: {
        cards: 61,
        turns: 13.5,
        deaths: 2.96,
        noWinner: 0.056,
      },
      medium: {
        cards: 93,
        turns: 19.7,
        deaths: 4.6,
        noWinner: 0.043,
      },
      long: {
        cards: 127,
        turns: 22.9,
        deaths: 5.66,
        noWinner: 0.021,
      },
    },
    "8": {
      short: {
        cards: 71,
        turns: 15.7,
        deaths: 3.69,
        noWinner: 0.06,
      },
      medium: {
        cards: 107,
        turns: 22.9,
        deaths: 5.38,
        noWinner: 0.05,
      },
      long: {
        cards: 137,
        turns: 26.6,
        deaths: 6.34,
        noWinner: 0.02,
      },
    },
    "9": {
      short: {
        cards: 81,
        turns: 17.9,
        deaths: 4.04,
        noWinner: 0.048,
      },
      medium: {
        cards: 121,
        turns: 26,
        deaths: 6.11,
        noWinner: 0.045,
      },
      long: {
        cards: 162,
        turns: 30.7,
        deaths: 7.52,
        noWinner: 0.018,
      },
    },
    "10": {
      short: {
        cards: 92,
        turns: 20.2,
        deaths: 4.8,
        noWinner: 0.055,
      },
      medium: {
        cards: 137,
        turns: 29.6,
        deaths: 7.02,
        noWinner: 0.046,
      },
      long: {
        cards: 183,
        turns: 34.6,
        deaths: 8.55,
        noWinner: 0.018,
      },
    },
    "11": {
      short: {
        cards: 103,
        turns: 22.7,
        deaths: 5.22,
        noWinner: 0.048,
      },
      medium: {
        cards: 151,
        turns: 32.7,
        deaths: 7.71,
        noWinner: 0.046,
      },
      long: {
        cards: 197,
        turns: 38.3,
        deaths: 9.4,
        noWinner: 0.022,
      },
    },
    "12": {
      short: {
        cards: 111,
        turns: 24.5,
        deaths: 5.64,
        noWinner: 0.051,
      },
      medium: {
        cards: 166,
        turns: 36,
        deaths: 8.52,
        noWinner: 0.048,
      },
      long: {
        cards: 211,
        turns: 41.8,
        deaths: 10.28,
        noWinner: 0.025,
      },
    },
  },
};
